title: KATBIN Blog
author: Asaph Binene
email: asaph@binene.com
Theme: minima
description: IT Hardware and software support and maintrnance, Database and System design and implimentation > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: @asaphbinene # DO NOT include the @ character, or else the build will fail!
github_username:  @asaphbinene # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
