theme: minima
title: Katbin Blog 
author: Asaph Binene
email: admin@katbin.com
description: > # this means to ignore newlines until "baseurl:"
  All about the KATBIN Brands from IT Support, Software and Database system managagement and design, system and business analysis.

# social links
twitter_username: @AsaphBinene # DO NOT include the @ character, or else the build will fail!
github_username:  @asaphbinene # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
